### ISSUE TITLE
Example config file

### ISSUE THREAD

**Issue by jcourcha** [Slashroot101/Discord-GambleBot-Bot#38]
Please provide example config file and needed database info to build bot

**Comment by Slashroot101** [comment]
Are you interested in forking it or do you want to add it to your discord server? It is not quite in a stable state yet as I am rewriting with NoSQL

**Comment by jcourcha** [comment]
No worries - was just trying it out :)

**Comment by Slashroot101** [comment]
I will ping you in a few weeks when it’s more stable and has more features. Stay tuned! I’ll also have it hosted.

**Comment by jcourcha** [comment]
Sounds good thanks!
